name: Checks

on:
  pull_request:
    # paths-ignore: [.vscode/**, .github/**]
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing dependencies
      run: npm ci

    - name: Linting Angular library
      run: npm run lint

  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Installing dependencies
  #     run: npm ci

  #   - name: Running all unit tests
  #     run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing dependencies
      run: npm ci

    - name: Building Angular library
      run: npm run build

