name: Publish

on:
  push:
    branches: [ main ]

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing dependencies
      run: npm ci

    - name: Building Angular library for production
      run: npm run build-prod

    - name: Publishing package to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        package: ./dist/nativescript-hide-action-bar


