name: Publish

on:
  push:
    # paths-ignore: [.vscode/**, .github/**]
    branches: [ main ]

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing dependencies
      run: npm ci

    - name: Building Angular library
      run: npm run build

